namespace crud_restaurant
{
    partial class FormManageMeja
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormManageMeja));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.guna2Panel1 = new Guna.UI2.WinForms.Guna2Panel();
            this.guna2PictureBox1 = new Guna.UI2.WinForms.Guna2PictureBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.guna2ControlBox1 = new Guna.UI2.WinForms.Guna2ControlBox();
            this.btn_delete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_update = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_insert = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dgv_manageMeja = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.txb_cari = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_cari = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txb_mejaID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txb_kodeMeja = new Bunifu.UI.WinForms.BunifuTextBox();
            this.guna2Panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.guna2PictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_manageMeja)).BeginInit();
            this.SuspendLayout();
            // 
            // guna2Panel1
            // 
            this.guna2Panel1.BackColor = System.Drawing.Color.White;
            this.guna2Panel1.Controls.Add(this.guna2PictureBox1);
            this.guna2Panel1.Controls.Add(this.bunifuLabel1);
            this.guna2Panel1.Controls.Add(this.guna2ControlBox1);
            this.guna2Panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.guna2Panel1.Location = new System.Drawing.Point(0, 0);
            this.guna2Panel1.Name = "guna2Panel1";
            this.guna2Panel1.ShadowDecoration.Parent = this.guna2Panel1;
            this.guna2Panel1.Size = new System.Drawing.Size(705, 40);
            this.guna2Panel1.TabIndex = 54;
            // 
            // guna2PictureBox1
            // 
            this.guna2PictureBox1.BackColor = System.Drawing.Color.White;
            this.guna2PictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("guna2PictureBox1.Image")));
            this.guna2PictureBox1.Location = new System.Drawing.Point(15, 10);
            this.guna2PictureBox1.Name = "guna2PictureBox1";
            this.guna2PictureBox1.ShadowDecoration.Parent = this.guna2PictureBox1;
            this.guna2PictureBox1.Size = new System.Drawing.Size(20, 20);
            this.guna2PictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.guna2PictureBox1.TabIndex = 2;
            this.guna2PictureBox1.TabStop = false;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.Location = new System.Drawing.Point(40, 10);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(110, 19);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Manage Meja";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // guna2ControlBox1
            // 
            this.guna2ControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.guna2ControlBox1.FillColor = System.Drawing.Color.Transparent;
            this.guna2ControlBox1.HoverState.BorderColor = System.Drawing.Color.Transparent;
            this.guna2ControlBox1.HoverState.FillColor = System.Drawing.Color.Red;
            this.guna2ControlBox1.HoverState.IconColor = System.Drawing.Color.White;
            this.guna2ControlBox1.HoverState.Parent = this.guna2ControlBox1;
            this.guna2ControlBox1.IconColor = System.Drawing.Color.Gray;
            this.guna2ControlBox1.Location = new System.Drawing.Point(655, 0);
            this.guna2ControlBox1.Name = "guna2ControlBox1";
            this.guna2ControlBox1.PressedColor = System.Drawing.Color.Maroon;
            this.guna2ControlBox1.ShadowDecoration.Parent = this.guna2ControlBox1;
            this.guna2ControlBox1.Size = new System.Drawing.Size(50, 40);
            this.guna2ControlBox1.TabIndex = 0;
            // 
            // btn_delete
            // 
            this.btn_delete.AllowAnimations = true;
            this.btn_delete.AllowMouseEffects = true;
            this.btn_delete.AllowToggling = false;
            this.btn_delete.AnimationSpeed = 200;
            this.btn_delete.AutoGenerateColors = false;
            this.btn_delete.AutoRoundBorders = false;
            this.btn_delete.AutoSizeLeftIcon = true;
            this.btn_delete.AutoSizeRightIcon = true;
            this.btn_delete.BackColor = System.Drawing.Color.Transparent;
            this.btn_delete.BackColor1 = System.Drawing.Color.Crimson;
            this.btn_delete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_delete.BackgroundImage")));
            this.btn_delete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.ButtonText = "Hapus";
            this.btn_delete.ButtonTextMarginLeft = 0;
            this.btn_delete.ColorContrastOnClick = 45;
            this.btn_delete.ColorContrastOnHover = 45;
            this.btn_delete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_delete.CustomizableEdges = borderEdges1;
            this.btn_delete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_delete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_delete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_delete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_delete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_delete.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_delete.ForeColor = System.Drawing.Color.White;
            this.btn_delete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_delete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_delete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_delete.IconMarginLeft = 11;
            this.btn_delete.IconPadding = 10;
            this.btn_delete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_delete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_delete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_delete.IconSize = 25;
            this.btn_delete.IdleBorderColor = System.Drawing.Color.Crimson;
            this.btn_delete.IdleBorderRadius = 15;
            this.btn_delete.IdleBorderThickness = 1;
            this.btn_delete.IdleFillColor = System.Drawing.Color.Crimson;
            this.btn_delete.IdleIconLeftImage = null;
            this.btn_delete.IdleIconRightImage = null;
            this.btn_delete.IndicateFocus = false;
            this.btn_delete.Location = new System.Drawing.Point(593, 307);
            this.btn_delete.Name = "btn_delete";
            this.btn_delete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_delete.OnDisabledState.BorderRadius = 15;
            this.btn_delete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.OnDisabledState.BorderThickness = 1;
            this.btn_delete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_delete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_delete.OnDisabledState.IconLeftImage = null;
            this.btn_delete.OnDisabledState.IconRightImage = null;
            this.btn_delete.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.btn_delete.onHoverState.BorderRadius = 15;
            this.btn_delete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.onHoverState.BorderThickness = 1;
            this.btn_delete.onHoverState.FillColor = System.Drawing.Color.Red;
            this.btn_delete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_delete.onHoverState.IconLeftImage = null;
            this.btn_delete.onHoverState.IconRightImage = null;
            this.btn_delete.OnIdleState.BorderColor = System.Drawing.Color.Crimson;
            this.btn_delete.OnIdleState.BorderRadius = 15;
            this.btn_delete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.OnIdleState.BorderThickness = 1;
            this.btn_delete.OnIdleState.FillColor = System.Drawing.Color.Crimson;
            this.btn_delete.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_delete.OnIdleState.IconLeftImage = null;
            this.btn_delete.OnIdleState.IconRightImage = null;
            this.btn_delete.OnPressedState.BorderColor = System.Drawing.Color.Maroon;
            this.btn_delete.OnPressedState.BorderRadius = 15;
            this.btn_delete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.OnPressedState.BorderThickness = 1;
            this.btn_delete.OnPressedState.FillColor = System.Drawing.Color.Maroon;
            this.btn_delete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_delete.OnPressedState.IconLeftImage = null;
            this.btn_delete.OnPressedState.IconRightImage = null;
            this.btn_delete.Size = new System.Drawing.Size(100, 35);
            this.btn_delete.TabIndex = 69;
            this.btn_delete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_delete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_delete.TextMarginLeft = 0;
            this.btn_delete.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_delete.UseDefaultRadiusAndThickness = true;
            // 
            // btn_update
            // 
            this.btn_update.AllowAnimations = true;
            this.btn_update.AllowMouseEffects = true;
            this.btn_update.AllowToggling = false;
            this.btn_update.AnimationSpeed = 200;
            this.btn_update.AutoGenerateColors = false;
            this.btn_update.AutoRoundBorders = false;
            this.btn_update.AutoSizeLeftIcon = true;
            this.btn_update.AutoSizeRightIcon = true;
            this.btn_update.BackColor = System.Drawing.Color.Transparent;
            this.btn_update.BackColor1 = System.Drawing.Color.Orange;
            this.btn_update.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_update.BackgroundImage")));
            this.btn_update.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_update.ButtonText = "Edit";
            this.btn_update.ButtonTextMarginLeft = 0;
            this.btn_update.ColorContrastOnClick = 45;
            this.btn_update.ColorContrastOnHover = 45;
            this.btn_update.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_update.CustomizableEdges = borderEdges2;
            this.btn_update.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_update.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_update.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_update.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_update.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_update.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_update.ForeColor = System.Drawing.Color.White;
            this.btn_update.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_update.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_update.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_update.IconMarginLeft = 11;
            this.btn_update.IconPadding = 10;
            this.btn_update.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_update.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_update.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_update.IconSize = 25;
            this.btn_update.IdleBorderColor = System.Drawing.Color.Orange;
            this.btn_update.IdleBorderRadius = 15;
            this.btn_update.IdleBorderThickness = 1;
            this.btn_update.IdleFillColor = System.Drawing.Color.Orange;
            this.btn_update.IdleIconLeftImage = null;
            this.btn_update.IdleIconRightImage = null;
            this.btn_update.IndicateFocus = false;
            this.btn_update.Location = new System.Drawing.Point(480, 307);
            this.btn_update.Name = "btn_update";
            this.btn_update.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_update.OnDisabledState.BorderRadius = 15;
            this.btn_update.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_update.OnDisabledState.BorderThickness = 1;
            this.btn_update.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_update.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_update.OnDisabledState.IconLeftImage = null;
            this.btn_update.OnDisabledState.IconRightImage = null;
            this.btn_update.onHoverState.BorderColor = System.Drawing.Color.Gold;
            this.btn_update.onHoverState.BorderRadius = 15;
            this.btn_update.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_update.onHoverState.BorderThickness = 1;
            this.btn_update.onHoverState.FillColor = System.Drawing.Color.Gold;
            this.btn_update.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_update.onHoverState.IconLeftImage = null;
            this.btn_update.onHoverState.IconRightImage = null;
            this.btn_update.OnIdleState.BorderColor = System.Drawing.Color.Orange;
            this.btn_update.OnIdleState.BorderRadius = 15;
            this.btn_update.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_update.OnIdleState.BorderThickness = 1;
            this.btn_update.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.btn_update.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_update.OnIdleState.IconLeftImage = null;
            this.btn_update.OnIdleState.IconRightImage = null;
            this.btn_update.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.btn_update.OnPressedState.BorderRadius = 15;
            this.btn_update.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_update.OnPressedState.BorderThickness = 1;
            this.btn_update.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.btn_update.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_update.OnPressedState.IconLeftImage = null;
            this.btn_update.OnPressedState.IconRightImage = null;
            this.btn_update.Size = new System.Drawing.Size(100, 35);
            this.btn_update.TabIndex = 68;
            this.btn_update.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_update.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_update.TextMarginLeft = 0;
            this.btn_update.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_update.UseDefaultRadiusAndThickness = true;
            // 
            // btn_insert
            // 
            this.btn_insert.AllowAnimations = true;
            this.btn_insert.AllowMouseEffects = true;
            this.btn_insert.AllowToggling = false;
            this.btn_insert.AnimationSpeed = 200;
            this.btn_insert.AutoGenerateColors = false;
            this.btn_insert.AutoRoundBorders = false;
            this.btn_insert.AutoSizeLeftIcon = true;
            this.btn_insert.AutoSizeRightIcon = true;
            this.btn_insert.BackColor = System.Drawing.Color.Transparent;
            this.btn_insert.BackColor1 = System.Drawing.Color.LimeGreen;
            this.btn_insert.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_insert.BackgroundImage")));
            this.btn_insert.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_insert.ButtonText = "Tambah";
            this.btn_insert.ButtonTextMarginLeft = 0;
            this.btn_insert.ColorContrastOnClick = 45;
            this.btn_insert.ColorContrastOnHover = 45;
            this.btn_insert.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_insert.CustomizableEdges = borderEdges3;
            this.btn_insert.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_insert.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_insert.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_insert.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_insert.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_insert.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_insert.ForeColor = System.Drawing.Color.White;
            this.btn_insert.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_insert.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_insert.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_insert.IconMarginLeft = 11;
            this.btn_insert.IconPadding = 10;
            this.btn_insert.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_insert.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_insert.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_insert.IconSize = 25;
            this.btn_insert.IdleBorderColor = System.Drawing.Color.LimeGreen;
            this.btn_insert.IdleBorderRadius = 15;
            this.btn_insert.IdleBorderThickness = 1;
            this.btn_insert.IdleFillColor = System.Drawing.Color.LimeGreen;
            this.btn_insert.IdleIconLeftImage = null;
            this.btn_insert.IdleIconRightImage = null;
            this.btn_insert.IndicateFocus = false;
            this.btn_insert.Location = new System.Drawing.Point(366, 307);
            this.btn_insert.Name = "btn_insert";
            this.btn_insert.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_insert.OnDisabledState.BorderRadius = 15;
            this.btn_insert.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_insert.OnDisabledState.BorderThickness = 1;
            this.btn_insert.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_insert.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_insert.OnDisabledState.IconLeftImage = null;
            this.btn_insert.OnDisabledState.IconRightImage = null;
            this.btn_insert.onHoverState.BorderColor = System.Drawing.Color.Lime;
            this.btn_insert.onHoverState.BorderRadius = 15;
            this.btn_insert.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_insert.onHoverState.BorderThickness = 1;
            this.btn_insert.onHoverState.FillColor = System.Drawing.Color.Lime;
            this.btn_insert.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_insert.onHoverState.IconLeftImage = null;
            this.btn_insert.onHoverState.IconRightImage = null;
            this.btn_insert.OnIdleState.BorderColor = System.Drawing.Color.LimeGreen;
            this.btn_insert.OnIdleState.BorderRadius = 15;
            this.btn_insert.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_insert.OnIdleState.BorderThickness = 1;
            this.btn_insert.OnIdleState.FillColor = System.Drawing.Color.LimeGreen;
            this.btn_insert.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_insert.OnIdleState.IconLeftImage = null;
            this.btn_insert.OnIdleState.IconRightImage = null;
            this.btn_insert.OnPressedState.BorderColor = System.Drawing.Color.Green;
            this.btn_insert.OnPressedState.BorderRadius = 15;
            this.btn_insert.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_insert.OnPressedState.BorderThickness = 1;
            this.btn_insert.OnPressedState.FillColor = System.Drawing.Color.Green;
            this.btn_insert.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_insert.OnPressedState.IconLeftImage = null;
            this.btn_insert.OnPressedState.IconRightImage = null;
            this.btn_insert.Size = new System.Drawing.Size(100, 35);
            this.btn_insert.TabIndex = 67;
            this.btn_insert.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_insert.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_insert.TextMarginLeft = 0;
            this.btn_insert.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_insert.UseDefaultRadiusAndThickness = true;
            // 
            // dgv_manageMeja
            // 
            this.dgv_manageMeja.AllowCustomTheming = false;
            this.dgv_manageMeja.AllowUserToOrderColumns = true;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dgv_manageMeja.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgv_manageMeja.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgv_manageMeja.BackgroundColor = System.Drawing.Color.White;
            this.dgv_manageMeja.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgv_manageMeja.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgv_manageMeja.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgv_manageMeja.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgv_manageMeja.ColumnHeadersHeight = 40;
            this.dgv_manageMeja.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgv_manageMeja.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgv_manageMeja.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgv_manageMeja.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgv_manageMeja.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgv_manageMeja.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgv_manageMeja.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgv_manageMeja.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgv_manageMeja.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgv_manageMeja.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgv_manageMeja.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgv_manageMeja.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgv_manageMeja.CurrentTheme.Name = null;
            this.dgv_manageMeja.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgv_manageMeja.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgv_manageMeja.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgv_manageMeja.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgv_manageMeja.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgv_manageMeja.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgv_manageMeja.EnableHeadersVisualStyles = false;
            this.dgv_manageMeja.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgv_manageMeja.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgv_manageMeja.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgv_manageMeja.HeaderForeColor = System.Drawing.Color.White;
            this.dgv_manageMeja.Location = new System.Drawing.Point(10, 85);
            this.dgv_manageMeja.Name = "dgv_manageMeja";
            this.dgv_manageMeja.RowHeadersVisible = false;
            this.dgv_manageMeja.RowTemplate.Height = 40;
            this.dgv_manageMeja.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgv_manageMeja.Size = new System.Drawing.Size(683, 175);
            this.dgv_manageMeja.TabIndex = 66;
            this.dgv_manageMeja.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // txb_cari
            // 
            this.txb_cari.AcceptsReturn = false;
            this.txb_cari.AcceptsTab = false;
            this.txb_cari.AnimationSpeed = 200;
            this.txb_cari.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txb_cari.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txb_cari.BackColor = System.Drawing.Color.Transparent;
            this.txb_cari.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txb_cari.BackgroundImage")));
            this.txb_cari.BorderColorActive = System.Drawing.Color.DimGray;
            this.txb_cari.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txb_cari.BorderColorHover = System.Drawing.Color.Gray;
            this.txb_cari.BorderColorIdle = System.Drawing.Color.Silver;
            this.txb_cari.BorderRadius = 15;
            this.txb_cari.BorderThickness = 1;
            this.txb_cari.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txb_cari.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_cari.DefaultFont = new System.Drawing.Font("Century Gothic", 8F);
            this.txb_cari.DefaultText = "";
            this.txb_cari.FillColor = System.Drawing.Color.White;
            this.txb_cari.HideSelection = true;
            this.txb_cari.IconLeft = null;
            this.txb_cari.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_cari.IconPadding = 10;
            this.txb_cari.IconRight = null;
            this.txb_cari.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_cari.Lines = new string[0];
            this.txb_cari.Location = new System.Drawing.Point(369, 48);
            this.txb_cari.MaxLength = 32767;
            this.txb_cari.MinimumSize = new System.Drawing.Size(1, 1);
            this.txb_cari.Modified = false;
            this.txb_cari.Multiline = false;
            this.txb_cari.Name = "txb_cari";
            stateProperties1.BorderColor = System.Drawing.Color.DimGray;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_cari.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txb_cari.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Gray;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_cari.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_cari.OnIdleState = stateProperties4;
            this.txb_cari.Padding = new System.Windows.Forms.Padding(3);
            this.txb_cari.PasswordChar = '\0';
            this.txb_cari.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txb_cari.PlaceholderText = "Search";
            this.txb_cari.ReadOnly = false;
            this.txb_cari.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txb_cari.SelectedText = "";
            this.txb_cari.SelectionLength = 0;
            this.txb_cari.SelectionStart = 0;
            this.txb_cari.ShortcutsEnabled = true;
            this.txb_cari.Size = new System.Drawing.Size(225, 34);
            this.txb_cari.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txb_cari.TabIndex = 60;
            this.txb_cari.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txb_cari.TextMarginBottom = 0;
            this.txb_cari.TextMarginLeft = 3;
            this.txb_cari.TextMarginTop = 0;
            this.txb_cari.TextPlaceholder = "Search";
            this.txb_cari.UseSystemPasswordChar = false;
            this.txb_cari.WordWrap = true;
            // 
            // btn_cari
            // 
            this.btn_cari.AllowAnimations = true;
            this.btn_cari.AllowMouseEffects = true;
            this.btn_cari.AllowToggling = false;
            this.btn_cari.AnimationSpeed = 200;
            this.btn_cari.AutoGenerateColors = false;
            this.btn_cari.AutoRoundBorders = false;
            this.btn_cari.AutoSizeLeftIcon = true;
            this.btn_cari.AutoSizeRightIcon = true;
            this.btn_cari.BackColor = System.Drawing.Color.Transparent;
            this.btn_cari.BackColor1 = System.Drawing.Color.Transparent;
            this.btn_cari.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_cari.BackgroundImage")));
            this.btn_cari.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cari.ButtonText = "Search";
            this.btn_cari.ButtonTextMarginLeft = 0;
            this.btn_cari.ColorContrastOnClick = 45;
            this.btn_cari.ColorContrastOnHover = 45;
            this.btn_cari.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_cari.CustomizableEdges = borderEdges4;
            this.btn_cari.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_cari.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_cari.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_cari.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_cari.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_cari.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_cari.ForeColor = System.Drawing.Color.Black;
            this.btn_cari.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_cari.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_cari.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_cari.IconMarginLeft = 11;
            this.btn_cari.IconPadding = 10;
            this.btn_cari.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_cari.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_cari.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_cari.IconSize = 25;
            this.btn_cari.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_cari.IdleBorderRadius = 1;
            this.btn_cari.IdleBorderThickness = 1;
            this.btn_cari.IdleFillColor = System.Drawing.Color.Transparent;
            this.btn_cari.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_cari.IdleIconLeftImage")));
            this.btn_cari.IdleIconRightImage = null;
            this.btn_cari.IndicateFocus = false;
            this.btn_cari.Location = new System.Drawing.Point(600, 45);
            this.btn_cari.Name = "btn_cari";
            this.btn_cari.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_cari.OnDisabledState.BorderRadius = 1;
            this.btn_cari.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cari.OnDisabledState.BorderThickness = 1;
            this.btn_cari.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_cari.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_cari.OnDisabledState.IconLeftImage = null;
            this.btn_cari.OnDisabledState.IconRightImage = null;
            this.btn_cari.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_cari.onHoverState.BorderRadius = 1;
            this.btn_cari.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cari.onHoverState.BorderThickness = 1;
            this.btn_cari.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.btn_cari.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btn_cari.onHoverState.IconLeftImage = null;
            this.btn_cari.onHoverState.IconRightImage = null;
            this.btn_cari.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_cari.OnIdleState.BorderRadius = 1;
            this.btn_cari.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cari.OnIdleState.BorderThickness = 1;
            this.btn_cari.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btn_cari.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btn_cari.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_cari.OnIdleState.IconLeftImage")));
            this.btn_cari.OnIdleState.IconRightImage = null;
            this.btn_cari.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_cari.OnPressedState.BorderRadius = 1;
            this.btn_cari.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cari.OnPressedState.BorderThickness = 1;
            this.btn_cari.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btn_cari.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btn_cari.OnPressedState.IconLeftImage = null;
            this.btn_cari.OnPressedState.IconRightImage = null;
            this.btn_cari.Size = new System.Drawing.Size(93, 39);
            this.btn_cari.TabIndex = 61;
            this.btn_cari.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_cari.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_cari.TextMarginLeft = 0;
            this.btn_cari.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_cari.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Century Gothic", 13F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel3.Location = new System.Drawing.Point(45, 280);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(73, 19);
            this.bunifuLabel3.TabIndex = 65;
            this.bunifuLabel3.Text = "Meja ID :";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txb_mejaID
            // 
            this.txb_mejaID.AcceptsReturn = false;
            this.txb_mejaID.AcceptsTab = false;
            this.txb_mejaID.AnimationSpeed = 200;
            this.txb_mejaID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txb_mejaID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txb_mejaID.BackColor = System.Drawing.Color.Transparent;
            this.txb_mejaID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txb_mejaID.BackgroundImage")));
            this.txb_mejaID.BorderColorActive = System.Drawing.Color.DimGray;
            this.txb_mejaID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txb_mejaID.BorderColorHover = System.Drawing.Color.Gray;
            this.txb_mejaID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txb_mejaID.BorderRadius = 15;
            this.txb_mejaID.BorderThickness = 1;
            this.txb_mejaID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txb_mejaID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_mejaID.DefaultFont = new System.Drawing.Font("Century Gothic", 7F);
            this.txb_mejaID.DefaultText = "";
            this.txb_mejaID.FillColor = System.Drawing.Color.White;
            this.txb_mejaID.HideSelection = true;
            this.txb_mejaID.IconLeft = null;
            this.txb_mejaID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_mejaID.IconPadding = 10;
            this.txb_mejaID.IconRight = null;
            this.txb_mejaID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_mejaID.Lines = new string[0];
            this.txb_mejaID.Location = new System.Drawing.Point(125, 275);
            this.txb_mejaID.MaxLength = 32767;
            this.txb_mejaID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txb_mejaID.Modified = false;
            this.txb_mejaID.Multiline = false;
            this.txb_mejaID.Name = "txb_mejaID";
            stateProperties5.BorderColor = System.Drawing.Color.DimGray;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_mejaID.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txb_mejaID.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Gray;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_mejaID.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_mejaID.OnIdleState = stateProperties8;
            this.txb_mejaID.Padding = new System.Windows.Forms.Padding(3);
            this.txb_mejaID.PasswordChar = '\0';
            this.txb_mejaID.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txb_mejaID.PlaceholderText = "ID";
            this.txb_mejaID.ReadOnly = false;
            this.txb_mejaID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txb_mejaID.SelectedText = "";
            this.txb_mejaID.SelectionLength = 0;
            this.txb_mejaID.SelectionStart = 0;
            this.txb_mejaID.ShortcutsEnabled = true;
            this.txb_mejaID.Size = new System.Drawing.Size(213, 32);
            this.txb_mejaID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txb_mejaID.TabIndex = 64;
            this.txb_mejaID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txb_mejaID.TextMarginBottom = 0;
            this.txb_mejaID.TextMarginLeft = 3;
            this.txb_mejaID.TextMarginTop = 0;
            this.txb_mejaID.TextPlaceholder = "ID";
            this.txb_mejaID.UseSystemPasswordChar = false;
            this.txb_mejaID.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Century Gothic", 13F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(18, 315);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(100, 19);
            this.bunifuLabel2.TabIndex = 63;
            this.bunifuLabel2.Text = "Kode Meja :";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txb_kodeMeja
            // 
            this.txb_kodeMeja.AcceptsReturn = false;
            this.txb_kodeMeja.AcceptsTab = false;
            this.txb_kodeMeja.AnimationSpeed = 200;
            this.txb_kodeMeja.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txb_kodeMeja.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txb_kodeMeja.BackColor = System.Drawing.Color.Transparent;
            this.txb_kodeMeja.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txb_kodeMeja.BackgroundImage")));
            this.txb_kodeMeja.BorderColorActive = System.Drawing.Color.DimGray;
            this.txb_kodeMeja.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txb_kodeMeja.BorderColorHover = System.Drawing.Color.Gray;
            this.txb_kodeMeja.BorderColorIdle = System.Drawing.Color.Silver;
            this.txb_kodeMeja.BorderRadius = 15;
            this.txb_kodeMeja.BorderThickness = 1;
            this.txb_kodeMeja.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txb_kodeMeja.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_kodeMeja.DefaultFont = new System.Drawing.Font("Century Gothic", 7F);
            this.txb_kodeMeja.DefaultText = "";
            this.txb_kodeMeja.FillColor = System.Drawing.Color.White;
            this.txb_kodeMeja.HideSelection = true;
            this.txb_kodeMeja.IconLeft = null;
            this.txb_kodeMeja.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_kodeMeja.IconPadding = 10;
            this.txb_kodeMeja.IconRight = null;
            this.txb_kodeMeja.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_kodeMeja.Lines = new string[0];
            this.txb_kodeMeja.Location = new System.Drawing.Point(125, 310);
            this.txb_kodeMeja.MaxLength = 32767;
            this.txb_kodeMeja.MinimumSize = new System.Drawing.Size(1, 1);
            this.txb_kodeMeja.Modified = false;
            this.txb_kodeMeja.Multiline = false;
            this.txb_kodeMeja.Name = "txb_kodeMeja";
            stateProperties9.BorderColor = System.Drawing.Color.DimGray;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_kodeMeja.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txb_kodeMeja.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Gray;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_kodeMeja.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_kodeMeja.OnIdleState = stateProperties12;
            this.txb_kodeMeja.Padding = new System.Windows.Forms.Padding(3);
            this.txb_kodeMeja.PasswordChar = '\0';
            this.txb_kodeMeja.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txb_kodeMeja.PlaceholderText = "Kode Meja";
            this.txb_kodeMeja.ReadOnly = false;
            this.txb_kodeMeja.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txb_kodeMeja.SelectedText = "";
            this.txb_kodeMeja.SelectionLength = 0;
            this.txb_kodeMeja.SelectionStart = 0;
            this.txb_kodeMeja.ShortcutsEnabled = true;
            this.txb_kodeMeja.Size = new System.Drawing.Size(213, 32);
            this.txb_kodeMeja.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txb_kodeMeja.TabIndex = 62;
            this.txb_kodeMeja.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txb_kodeMeja.TextMarginBottom = 0;
            this.txb_kodeMeja.TextMarginLeft = 3;
            this.txb_kodeMeja.TextMarginTop = 0;
            this.txb_kodeMeja.TextPlaceholder = "Kode Meja";
            this.txb_kodeMeja.UseSystemPasswordChar = false;
            this.txb_kodeMeja.WordWrap = true;
            // 
            // FormManageMeja
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(243)))), ((int)(((byte)(224)))));
            this.ClientSize = new System.Drawing.Size(705, 365);
            this.ControlBox = false;
            this.Controls.Add(this.btn_delete);
            this.Controls.Add(this.btn_update);
            this.Controls.Add(this.btn_insert);
            this.Controls.Add(this.dgv_manageMeja);
            this.Controls.Add(this.txb_cari);
            this.Controls.Add(this.btn_cari);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.txb_mejaID);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.txb_kodeMeja);
            this.Controls.Add(this.guna2Panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormManageMeja";
            this.guna2Panel1.ResumeLayout(false);
            this.guna2Panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.guna2PictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_manageMeja)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Guna.UI2.WinForms.Guna2Panel guna2Panel1;
        private Guna.UI2.WinForms.Guna2PictureBox guna2PictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Guna.UI2.WinForms.Guna2ControlBox guna2ControlBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_delete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_update;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_insert;
        private Bunifu.UI.WinForms.BunifuDataGridView dgv_manageMeja;
        private Bunifu.UI.WinForms.BunifuTextBox txb_cari;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_cari;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox txb_mejaID;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox txb_kodeMeja;
    }
}