
namespace crud_restaurant
{
    partial class FormManageMenu
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormManageMenu));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.txb_cari = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_cari = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dgv_manageMenu = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.guna2Panel1 = new Guna.UI2.WinForms.Guna2Panel();
            this.guna2PictureBox1 = new Guna.UI2.WinForms.Guna2PictureBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.guna2ControlBox1 = new Guna.UI2.WinForms.Guna2ControlBox();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.cb_kategori = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txb_hargaMenu = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txb_menuID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txb_namaMenu = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txb_filePath = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_pickFile = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_delete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_update = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_insert = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pb_fotoFile = new Guna.UI2.WinForms.Guna2PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_manageMenu)).BeginInit();
            this.guna2Panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.guna2PictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pb_fotoFile)).BeginInit();
            this.SuspendLayout();
            // 
            // txb_cari
            // 
            this.txb_cari.AcceptsReturn = false;
            this.txb_cari.AcceptsTab = false;
            this.txb_cari.AnimationSpeed = 200;
            this.txb_cari.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txb_cari.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txb_cari.BackColor = System.Drawing.Color.Transparent;
            this.txb_cari.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txb_cari.BackgroundImage")));
            this.txb_cari.BorderColorActive = System.Drawing.Color.DimGray;
            this.txb_cari.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txb_cari.BorderColorHover = System.Drawing.Color.Gray;
            this.txb_cari.BorderColorIdle = System.Drawing.Color.Silver;
            this.txb_cari.BorderRadius = 15;
            this.txb_cari.BorderThickness = 1;
            this.txb_cari.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txb_cari.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_cari.DefaultFont = new System.Drawing.Font("Century Gothic", 8F);
            this.txb_cari.DefaultText = "";
            this.txb_cari.FillColor = System.Drawing.Color.White;
            this.txb_cari.HideSelection = true;
            this.txb_cari.IconLeft = null;
            this.txb_cari.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_cari.IconPadding = 10;
            this.txb_cari.IconRight = null;
            this.txb_cari.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_cari.Lines = new string[0];
            this.txb_cari.Location = new System.Drawing.Point(384, 45);
            this.txb_cari.MaxLength = 32767;
            this.txb_cari.MinimumSize = new System.Drawing.Size(1, 1);
            this.txb_cari.Modified = false;
            this.txb_cari.Multiline = false;
            this.txb_cari.Name = "txb_cari";
            stateProperties1.BorderColor = System.Drawing.Color.DimGray;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_cari.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txb_cari.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Gray;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_cari.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_cari.OnIdleState = stateProperties4;
            this.txb_cari.Padding = new System.Windows.Forms.Padding(3);
            this.txb_cari.PasswordChar = '\0';
            this.txb_cari.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txb_cari.PlaceholderText = "Search";
            this.txb_cari.ReadOnly = false;
            this.txb_cari.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txb_cari.SelectedText = "";
            this.txb_cari.SelectionLength = 0;
            this.txb_cari.SelectionStart = 0;
            this.txb_cari.ShortcutsEnabled = true;
            this.txb_cari.Size = new System.Drawing.Size(225, 34);
            this.txb_cari.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txb_cari.TabIndex = 34;
            this.txb_cari.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txb_cari.TextMarginBottom = 0;
            this.txb_cari.TextMarginLeft = 3;
            this.txb_cari.TextMarginTop = 0;
            this.txb_cari.TextPlaceholder = "Search";
            this.txb_cari.UseSystemPasswordChar = false;
            this.txb_cari.WordWrap = true;
            this.txb_cari.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txb_cari_KeyDown);
            // 
            // btn_cari
            // 
            this.btn_cari.AllowAnimations = true;
            this.btn_cari.AllowMouseEffects = true;
            this.btn_cari.AllowToggling = false;
            this.btn_cari.AnimationSpeed = 200;
            this.btn_cari.AutoGenerateColors = false;
            this.btn_cari.AutoRoundBorders = false;
            this.btn_cari.AutoSizeLeftIcon = true;
            this.btn_cari.AutoSizeRightIcon = true;
            this.btn_cari.BackColor = System.Drawing.Color.Transparent;
            this.btn_cari.BackColor1 = System.Drawing.Color.Transparent;
            this.btn_cari.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_cari.BackgroundImage")));
            this.btn_cari.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cari.ButtonText = "Search";
            this.btn_cari.ButtonTextMarginLeft = 0;
            this.btn_cari.ColorContrastOnClick = 45;
            this.btn_cari.ColorContrastOnHover = 45;
            this.btn_cari.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_cari.CustomizableEdges = borderEdges1;
            this.btn_cari.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_cari.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_cari.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_cari.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_cari.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_cari.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_cari.ForeColor = System.Drawing.Color.Black;
            this.btn_cari.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_cari.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_cari.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_cari.IconMarginLeft = 11;
            this.btn_cari.IconPadding = 10;
            this.btn_cari.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_cari.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_cari.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_cari.IconSize = 25;
            this.btn_cari.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_cari.IdleBorderRadius = 1;
            this.btn_cari.IdleBorderThickness = 1;
            this.btn_cari.IdleFillColor = System.Drawing.Color.Transparent;
            this.btn_cari.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_cari.IdleIconLeftImage")));
            this.btn_cari.IdleIconRightImage = null;
            this.btn_cari.IndicateFocus = false;
            this.btn_cari.Location = new System.Drawing.Point(615, 42);
            this.btn_cari.Name = "btn_cari";
            this.btn_cari.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_cari.OnDisabledState.BorderRadius = 1;
            this.btn_cari.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cari.OnDisabledState.BorderThickness = 1;
            this.btn_cari.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_cari.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_cari.OnDisabledState.IconLeftImage = null;
            this.btn_cari.OnDisabledState.IconRightImage = null;
            this.btn_cari.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_cari.onHoverState.BorderRadius = 1;
            this.btn_cari.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cari.onHoverState.BorderThickness = 1;
            this.btn_cari.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.btn_cari.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btn_cari.onHoverState.IconLeftImage = null;
            this.btn_cari.onHoverState.IconRightImage = null;
            this.btn_cari.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_cari.OnIdleState.BorderRadius = 1;
            this.btn_cari.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cari.OnIdleState.BorderThickness = 1;
            this.btn_cari.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btn_cari.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btn_cari.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_cari.OnIdleState.IconLeftImage")));
            this.btn_cari.OnIdleState.IconRightImage = null;
            this.btn_cari.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_cari.OnPressedState.BorderRadius = 1;
            this.btn_cari.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cari.OnPressedState.BorderThickness = 1;
            this.btn_cari.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btn_cari.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btn_cari.OnPressedState.IconLeftImage = null;
            this.btn_cari.OnPressedState.IconRightImage = null;
            this.btn_cari.Size = new System.Drawing.Size(93, 39);
            this.btn_cari.TabIndex = 35;
            this.btn_cari.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_cari.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_cari.TextMarginLeft = 0;
            this.btn_cari.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_cari.UseDefaultRadiusAndThickness = true;
            this.btn_cari.Click += new System.EventHandler(this.btn_cari_Click);
            // 
            // dgv_manageMenu
            // 
            this.dgv_manageMenu.AllowCustomTheming = false;
            this.dgv_manageMenu.AllowUserToOrderColumns = true;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dgv_manageMenu.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgv_manageMenu.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgv_manageMenu.BackgroundColor = System.Drawing.Color.White;
            this.dgv_manageMenu.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgv_manageMenu.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgv_manageMenu.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgv_manageMenu.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgv_manageMenu.ColumnHeadersHeight = 40;
            this.dgv_manageMenu.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgv_manageMenu.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgv_manageMenu.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgv_manageMenu.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgv_manageMenu.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgv_manageMenu.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgv_manageMenu.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgv_manageMenu.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgv_manageMenu.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgv_manageMenu.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgv_manageMenu.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgv_manageMenu.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgv_manageMenu.CurrentTheme.Name = null;
            this.dgv_manageMenu.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgv_manageMenu.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgv_manageMenu.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgv_manageMenu.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgv_manageMenu.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgv_manageMenu.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgv_manageMenu.EnableHeadersVisualStyles = false;
            this.dgv_manageMenu.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgv_manageMenu.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgv_manageMenu.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgv_manageMenu.HeaderForeColor = System.Drawing.Color.White;
            this.dgv_manageMenu.Location = new System.Drawing.Point(10, 85);
            this.dgv_manageMenu.Name = "dgv_manageMenu";
            this.dgv_manageMenu.RowHeadersVisible = false;
            this.dgv_manageMenu.RowTemplate.Height = 40;
            this.dgv_manageMenu.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgv_manageMenu.Size = new System.Drawing.Size(700, 175);
            this.dgv_manageMenu.TabIndex = 52;
            this.dgv_manageMenu.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // guna2Panel1
            // 
            this.guna2Panel1.BackColor = System.Drawing.Color.White;
            this.guna2Panel1.Controls.Add(this.guna2PictureBox1);
            this.guna2Panel1.Controls.Add(this.bunifuLabel1);
            this.guna2Panel1.Controls.Add(this.guna2ControlBox1);
            this.guna2Panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.guna2Panel1.Location = new System.Drawing.Point(0, 0);
            this.guna2Panel1.Name = "guna2Panel1";
            this.guna2Panel1.ShadowDecoration.Parent = this.guna2Panel1;
            this.guna2Panel1.Size = new System.Drawing.Size(720, 40);
            this.guna2Panel1.TabIndex = 53;
            // 
            // guna2PictureBox1
            // 
            this.guna2PictureBox1.BackColor = System.Drawing.Color.White;
            this.guna2PictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("guna2PictureBox1.Image")));
            this.guna2PictureBox1.Location = new System.Drawing.Point(15, 10);
            this.guna2PictureBox1.Name = "guna2PictureBox1";
            this.guna2PictureBox1.ShadowDecoration.Parent = this.guna2PictureBox1;
            this.guna2PictureBox1.Size = new System.Drawing.Size(20, 20);
            this.guna2PictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.guna2PictureBox1.TabIndex = 2;
            this.guna2PictureBox1.TabStop = false;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.Location = new System.Drawing.Point(40, 10);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(115, 19);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Manage Menu";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // guna2ControlBox1
            // 
            this.guna2ControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.guna2ControlBox1.FillColor = System.Drawing.Color.Transparent;
            this.guna2ControlBox1.HoverState.BorderColor = System.Drawing.Color.Transparent;
            this.guna2ControlBox1.HoverState.FillColor = System.Drawing.Color.Red;
            this.guna2ControlBox1.HoverState.IconColor = System.Drawing.Color.White;
            this.guna2ControlBox1.HoverState.Parent = this.guna2ControlBox1;
            this.guna2ControlBox1.IconColor = System.Drawing.Color.Gray;
            this.guna2ControlBox1.Location = new System.Drawing.Point(670, 0);
            this.guna2ControlBox1.Name = "guna2ControlBox1";
            this.guna2ControlBox1.PressedColor = System.Drawing.Color.Maroon;
            this.guna2ControlBox1.ShadowDecoration.Parent = this.guna2ControlBox1;
            this.guna2ControlBox1.Size = new System.Drawing.Size(50, 40);
            this.guna2ControlBox1.TabIndex = 0;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 30;
            this.bunifuElipse1.TargetControl = this;
            // 
            // cb_kategori
            // 
            this.cb_kategori.BackColor = System.Drawing.Color.Transparent;
            this.cb_kategori.BackgroundColor = System.Drawing.Color.White;
            this.cb_kategori.BorderColor = System.Drawing.Color.Silver;
            this.cb_kategori.BorderRadius = 5;
            this.cb_kategori.Color = System.Drawing.Color.Silver;
            this.cb_kategori.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cb_kategori.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cb_kategori.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cb_kategori.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cb_kategori.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cb_kategori.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cb_kategori.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cb_kategori.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cb_kategori.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cb_kategori.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cb_kategori.FillDropDown = true;
            this.cb_kategori.FillIndicator = false;
            this.cb_kategori.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cb_kategori.Font = new System.Drawing.Font("Century Gothic", 7F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cb_kategori.ForeColor = System.Drawing.Color.Black;
            this.cb_kategori.FormattingEnabled = true;
            this.cb_kategori.Icon = null;
            this.cb_kategori.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cb_kategori.IndicatorColor = System.Drawing.Color.Gray;
            this.cb_kategori.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cb_kategori.ItemBackColor = System.Drawing.Color.White;
            this.cb_kategori.ItemBorderColor = System.Drawing.Color.White;
            this.cb_kategori.ItemForeColor = System.Drawing.Color.Black;
            this.cb_kategori.ItemHeight = 26;
            this.cb_kategori.ItemHighLightColor = System.Drawing.Color.Gray;
            this.cb_kategori.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cb_kategori.Items.AddRange(new object[] {
            "Coffee",
            "Non-Coffee"});
            this.cb_kategori.ItemTopMargin = 3;
            this.cb_kategori.Location = new System.Drawing.Point(125, 383);
            this.cb_kategori.Name = "cb_kategori";
            this.cb_kategori.Size = new System.Drawing.Size(213, 32);
            this.cb_kategori.TabIndex = 53;
            this.cb_kategori.Text = null;
            this.cb_kategori.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cb_kategori.TextLeftMargin = 5;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Century Gothic", 13F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel7.Location = new System.Drawing.Point(40, 388);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(78, 19);
            this.bunifuLabel7.TabIndex = 52;
            this.bunifuLabel7.Text = "Kategori :";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Century Gothic", 13F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel4.Location = new System.Drawing.Point(61, 350);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(60, 19);
            this.bunifuLabel4.TabIndex = 51;
            this.bunifuLabel4.Text = "Harga :";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txb_hargaMenu
            // 
            this.txb_hargaMenu.AcceptsReturn = false;
            this.txb_hargaMenu.AcceptsTab = false;
            this.txb_hargaMenu.AnimationSpeed = 200;
            this.txb_hargaMenu.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txb_hargaMenu.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txb_hargaMenu.BackColor = System.Drawing.Color.Transparent;
            this.txb_hargaMenu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txb_hargaMenu.BackgroundImage")));
            this.txb_hargaMenu.BorderColorActive = System.Drawing.Color.DimGray;
            this.txb_hargaMenu.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txb_hargaMenu.BorderColorHover = System.Drawing.Color.Gray;
            this.txb_hargaMenu.BorderColorIdle = System.Drawing.Color.Silver;
            this.txb_hargaMenu.BorderRadius = 15;
            this.txb_hargaMenu.BorderThickness = 1;
            this.txb_hargaMenu.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txb_hargaMenu.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_hargaMenu.DefaultFont = new System.Drawing.Font("Century Gothic", 7F);
            this.txb_hargaMenu.DefaultText = "";
            this.txb_hargaMenu.FillColor = System.Drawing.Color.White;
            this.txb_hargaMenu.HideSelection = true;
            this.txb_hargaMenu.IconLeft = null;
            this.txb_hargaMenu.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_hargaMenu.IconPadding = 10;
            this.txb_hargaMenu.IconRight = null;
            this.txb_hargaMenu.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_hargaMenu.Lines = new string[0];
            this.txb_hargaMenu.Location = new System.Drawing.Point(125, 345);
            this.txb_hargaMenu.MaxLength = 32767;
            this.txb_hargaMenu.MinimumSize = new System.Drawing.Size(1, 1);
            this.txb_hargaMenu.Modified = false;
            this.txb_hargaMenu.Multiline = false;
            this.txb_hargaMenu.Name = "txb_hargaMenu";
            stateProperties9.BorderColor = System.Drawing.Color.DimGray;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_hargaMenu.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txb_hargaMenu.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Gray;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_hargaMenu.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_hargaMenu.OnIdleState = stateProperties12;
            this.txb_hargaMenu.Padding = new System.Windows.Forms.Padding(3);
            this.txb_hargaMenu.PasswordChar = '\0';
            this.txb_hargaMenu.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txb_hargaMenu.PlaceholderText = "Harga";
            this.txb_hargaMenu.ReadOnly = false;
            this.txb_hargaMenu.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txb_hargaMenu.SelectedText = "";
            this.txb_hargaMenu.SelectionLength = 0;
            this.txb_hargaMenu.SelectionStart = 0;
            this.txb_hargaMenu.ShortcutsEnabled = true;
            this.txb_hargaMenu.Size = new System.Drawing.Size(213, 32);
            this.txb_hargaMenu.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txb_hargaMenu.TabIndex = 50;
            this.txb_hargaMenu.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txb_hargaMenu.TextMarginBottom = 0;
            this.txb_hargaMenu.TextMarginLeft = 3;
            this.txb_hargaMenu.TextMarginTop = 0;
            this.txb_hargaMenu.TextPlaceholder = "Harga";
            this.txb_hargaMenu.UseSystemPasswordChar = false;
            this.txb_hargaMenu.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Century Gothic", 13F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel3.Location = new System.Drawing.Point(43, 279);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(78, 19);
            this.bunifuLabel3.TabIndex = 49;
            this.bunifuLabel3.Text = "Menu ID :";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txb_menuID
            // 
            this.txb_menuID.AcceptsReturn = false;
            this.txb_menuID.AcceptsTab = false;
            this.txb_menuID.AnimationSpeed = 200;
            this.txb_menuID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txb_menuID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txb_menuID.BackColor = System.Drawing.Color.Transparent;
            this.txb_menuID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txb_menuID.BackgroundImage")));
            this.txb_menuID.BorderColorActive = System.Drawing.Color.DimGray;
            this.txb_menuID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txb_menuID.BorderColorHover = System.Drawing.Color.Gray;
            this.txb_menuID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txb_menuID.BorderRadius = 15;
            this.txb_menuID.BorderThickness = 1;
            this.txb_menuID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txb_menuID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_menuID.DefaultFont = new System.Drawing.Font("Century Gothic", 7F);
            this.txb_menuID.DefaultText = "";
            this.txb_menuID.FillColor = System.Drawing.Color.White;
            this.txb_menuID.HideSelection = true;
            this.txb_menuID.IconLeft = null;
            this.txb_menuID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_menuID.IconPadding = 10;
            this.txb_menuID.IconRight = null;
            this.txb_menuID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_menuID.Lines = new string[0];
            this.txb_menuID.Location = new System.Drawing.Point(125, 275);
            this.txb_menuID.MaxLength = 32767;
            this.txb_menuID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txb_menuID.Modified = false;
            this.txb_menuID.Multiline = false;
            this.txb_menuID.Name = "txb_menuID";
            stateProperties13.BorderColor = System.Drawing.Color.DimGray;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_menuID.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txb_menuID.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Gray;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_menuID.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_menuID.OnIdleState = stateProperties16;
            this.txb_menuID.Padding = new System.Windows.Forms.Padding(3);
            this.txb_menuID.PasswordChar = '\0';
            this.txb_menuID.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txb_menuID.PlaceholderText = "ID";
            this.txb_menuID.ReadOnly = false;
            this.txb_menuID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txb_menuID.SelectedText = "";
            this.txb_menuID.SelectionLength = 0;
            this.txb_menuID.SelectionStart = 0;
            this.txb_menuID.ShortcutsEnabled = true;
            this.txb_menuID.Size = new System.Drawing.Size(213, 32);
            this.txb_menuID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txb_menuID.TabIndex = 48;
            this.txb_menuID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txb_menuID.TextMarginBottom = 0;
            this.txb_menuID.TextMarginLeft = 3;
            this.txb_menuID.TextMarginTop = 0;
            this.txb_menuID.TextPlaceholder = "ID";
            this.txb_menuID.UseSystemPasswordChar = false;
            this.txb_menuID.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Century Gothic", 13F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(9, 314);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(112, 19);
            this.bunifuLabel2.TabIndex = 47;
            this.bunifuLabel2.Text = "Nama Menu :";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txb_namaMenu
            // 
            this.txb_namaMenu.AcceptsReturn = false;
            this.txb_namaMenu.AcceptsTab = false;
            this.txb_namaMenu.AnimationSpeed = 200;
            this.txb_namaMenu.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txb_namaMenu.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txb_namaMenu.BackColor = System.Drawing.Color.Transparent;
            this.txb_namaMenu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txb_namaMenu.BackgroundImage")));
            this.txb_namaMenu.BorderColorActive = System.Drawing.Color.DimGray;
            this.txb_namaMenu.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txb_namaMenu.BorderColorHover = System.Drawing.Color.Gray;
            this.txb_namaMenu.BorderColorIdle = System.Drawing.Color.Silver;
            this.txb_namaMenu.BorderRadius = 15;
            this.txb_namaMenu.BorderThickness = 1;
            this.txb_namaMenu.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txb_namaMenu.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_namaMenu.DefaultFont = new System.Drawing.Font("Century Gothic", 7F);
            this.txb_namaMenu.DefaultText = "";
            this.txb_namaMenu.FillColor = System.Drawing.Color.White;
            this.txb_namaMenu.HideSelection = true;
            this.txb_namaMenu.IconLeft = null;
            this.txb_namaMenu.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_namaMenu.IconPadding = 10;
            this.txb_namaMenu.IconRight = null;
            this.txb_namaMenu.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_namaMenu.Lines = new string[0];
            this.txb_namaMenu.Location = new System.Drawing.Point(125, 310);
            this.txb_namaMenu.MaxLength = 32767;
            this.txb_namaMenu.MinimumSize = new System.Drawing.Size(1, 1);
            this.txb_namaMenu.Modified = false;
            this.txb_namaMenu.Multiline = false;
            this.txb_namaMenu.Name = "txb_namaMenu";
            stateProperties17.BorderColor = System.Drawing.Color.DimGray;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_namaMenu.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txb_namaMenu.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Gray;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_namaMenu.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_namaMenu.OnIdleState = stateProperties20;
            this.txb_namaMenu.Padding = new System.Windows.Forms.Padding(3);
            this.txb_namaMenu.PasswordChar = '\0';
            this.txb_namaMenu.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txb_namaMenu.PlaceholderText = "Nama Menu";
            this.txb_namaMenu.ReadOnly = false;
            this.txb_namaMenu.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txb_namaMenu.SelectedText = "";
            this.txb_namaMenu.SelectionLength = 0;
            this.txb_namaMenu.SelectionStart = 0;
            this.txb_namaMenu.ShortcutsEnabled = true;
            this.txb_namaMenu.Size = new System.Drawing.Size(213, 32);
            this.txb_namaMenu.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txb_namaMenu.TabIndex = 46;
            this.txb_namaMenu.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txb_namaMenu.TextMarginBottom = 0;
            this.txb_namaMenu.TextMarginLeft = 3;
            this.txb_namaMenu.TextMarginTop = 0;
            this.txb_namaMenu.TextPlaceholder = "Nama Menu";
            this.txb_namaMenu.UseSystemPasswordChar = false;
            this.txb_namaMenu.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Century Gothic", 13F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel5.Location = new System.Drawing.Point(75, 425);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(44, 19);
            this.bunifuLabel5.TabIndex = 55;
            this.bunifuLabel5.Text = "Foto :";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txb_filePath
            // 
            this.txb_filePath.AcceptsReturn = false;
            this.txb_filePath.AcceptsTab = false;
            this.txb_filePath.AnimationSpeed = 200;
            this.txb_filePath.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txb_filePath.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txb_filePath.BackColor = System.Drawing.Color.Transparent;
            this.txb_filePath.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txb_filePath.BackgroundImage")));
            this.txb_filePath.BorderColorActive = System.Drawing.Color.DimGray;
            this.txb_filePath.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txb_filePath.BorderColorHover = System.Drawing.Color.Gray;
            this.txb_filePath.BorderColorIdle = System.Drawing.Color.Silver;
            this.txb_filePath.BorderRadius = 15;
            this.txb_filePath.BorderThickness = 1;
            this.txb_filePath.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txb_filePath.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_filePath.DefaultFont = new System.Drawing.Font("Century Gothic", 7F);
            this.txb_filePath.DefaultText = "";
            this.txb_filePath.FillColor = System.Drawing.Color.White;
            this.txb_filePath.HideSelection = true;
            this.txb_filePath.IconLeft = null;
            this.txb_filePath.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_filePath.IconPadding = 10;
            this.txb_filePath.IconRight = null;
            this.txb_filePath.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txb_filePath.Lines = new string[0];
            this.txb_filePath.Location = new System.Drawing.Point(125, 421);
            this.txb_filePath.MaxLength = 32767;
            this.txb_filePath.MinimumSize = new System.Drawing.Size(1, 1);
            this.txb_filePath.Modified = false;
            this.txb_filePath.Multiline = false;
            this.txb_filePath.Name = "txb_filePath";
            stateProperties5.BorderColor = System.Drawing.Color.DimGray;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_filePath.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txb_filePath.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Gray;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_filePath.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txb_filePath.OnIdleState = stateProperties8;
            this.txb_filePath.Padding = new System.Windows.Forms.Padding(3);
            this.txb_filePath.PasswordChar = '\0';
            this.txb_filePath.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txb_filePath.PlaceholderText = "> 100kb";
            this.txb_filePath.ReadOnly = true;
            this.txb_filePath.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txb_filePath.SelectedText = "";
            this.txb_filePath.SelectionLength = 0;
            this.txb_filePath.SelectionStart = 0;
            this.txb_filePath.ShortcutsEnabled = true;
            this.txb_filePath.Size = new System.Drawing.Size(152, 32);
            this.txb_filePath.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txb_filePath.TabIndex = 54;
            this.txb_filePath.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txb_filePath.TextMarginBottom = 0;
            this.txb_filePath.TextMarginLeft = 3;
            this.txb_filePath.TextMarginTop = 0;
            this.txb_filePath.TextPlaceholder = "> 100kb";
            this.txb_filePath.UseSystemPasswordChar = false;
            this.txb_filePath.WordWrap = true;
            // 
            // btn_pickFile
            // 
            this.btn_pickFile.AllowAnimations = true;
            this.btn_pickFile.AllowMouseEffects = true;
            this.btn_pickFile.AllowToggling = false;
            this.btn_pickFile.AnimationSpeed = 200;
            this.btn_pickFile.AutoGenerateColors = false;
            this.btn_pickFile.AutoRoundBorders = false;
            this.btn_pickFile.AutoSizeLeftIcon = true;
            this.btn_pickFile.AutoSizeRightIcon = true;
            this.btn_pickFile.BackColor = System.Drawing.Color.Transparent;
            this.btn_pickFile.BackColor1 = System.Drawing.Color.DarkGray;
            this.btn_pickFile.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_pickFile.BackgroundImage")));
            this.btn_pickFile.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_pickFile.ButtonText = "...";
            this.btn_pickFile.ButtonTextMarginLeft = 0;
            this.btn_pickFile.ColorContrastOnClick = 45;
            this.btn_pickFile.ColorContrastOnHover = 45;
            this.btn_pickFile.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_pickFile.CustomizableEdges = borderEdges5;
            this.btn_pickFile.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_pickFile.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_pickFile.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_pickFile.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_pickFile.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_pickFile.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_pickFile.ForeColor = System.Drawing.Color.White;
            this.btn_pickFile.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_pickFile.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_pickFile.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_pickFile.IconMarginLeft = 11;
            this.btn_pickFile.IconPadding = 10;
            this.btn_pickFile.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_pickFile.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_pickFile.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_pickFile.IconSize = 25;
            this.btn_pickFile.IdleBorderColor = System.Drawing.Color.DarkGray;
            this.btn_pickFile.IdleBorderRadius = 1;
            this.btn_pickFile.IdleBorderThickness = 1;
            this.btn_pickFile.IdleFillColor = System.Drawing.Color.DarkGray;
            this.btn_pickFile.IdleIconLeftImage = null;
            this.btn_pickFile.IdleIconRightImage = null;
            this.btn_pickFile.IndicateFocus = false;
            this.btn_pickFile.Location = new System.Drawing.Point(283, 425);
            this.btn_pickFile.Name = "btn_pickFile";
            this.btn_pickFile.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_pickFile.OnDisabledState.BorderRadius = 1;
            this.btn_pickFile.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_pickFile.OnDisabledState.BorderThickness = 1;
            this.btn_pickFile.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_pickFile.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_pickFile.OnDisabledState.IconLeftImage = null;
            this.btn_pickFile.OnDisabledState.IconRightImage = null;
            this.btn_pickFile.onHoverState.BorderColor = System.Drawing.Color.Silver;
            this.btn_pickFile.onHoverState.BorderRadius = 1;
            this.btn_pickFile.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_pickFile.onHoverState.BorderThickness = 1;
            this.btn_pickFile.onHoverState.FillColor = System.Drawing.Color.Silver;
            this.btn_pickFile.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_pickFile.onHoverState.IconLeftImage = null;
            this.btn_pickFile.onHoverState.IconRightImage = null;
            this.btn_pickFile.OnIdleState.BorderColor = System.Drawing.Color.DarkGray;
            this.btn_pickFile.OnIdleState.BorderRadius = 1;
            this.btn_pickFile.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_pickFile.OnIdleState.BorderThickness = 1;
            this.btn_pickFile.OnIdleState.FillColor = System.Drawing.Color.DarkGray;
            this.btn_pickFile.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_pickFile.OnIdleState.IconLeftImage = null;
            this.btn_pickFile.OnIdleState.IconRightImage = null;
            this.btn_pickFile.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.btn_pickFile.OnPressedState.BorderRadius = 1;
            this.btn_pickFile.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_pickFile.OnPressedState.BorderThickness = 1;
            this.btn_pickFile.OnPressedState.FillColor = System.Drawing.Color.Gray;
            this.btn_pickFile.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_pickFile.OnPressedState.IconLeftImage = null;
            this.btn_pickFile.OnPressedState.IconRightImage = null;
            this.btn_pickFile.Size = new System.Drawing.Size(55, 23);
            this.btn_pickFile.TabIndex = 56;
            this.btn_pickFile.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_pickFile.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_pickFile.TextMarginLeft = 0;
            this.btn_pickFile.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_pickFile.UseDefaultRadiusAndThickness = true;
            this.btn_pickFile.Click += new System.EventHandler(this.btn_pickFile_Click);
            // 
            // btn_delete
            // 
            this.btn_delete.AllowAnimations = true;
            this.btn_delete.AllowMouseEffects = true;
            this.btn_delete.AllowToggling = false;
            this.btn_delete.AnimationSpeed = 200;
            this.btn_delete.AutoGenerateColors = false;
            this.btn_delete.AutoRoundBorders = false;
            this.btn_delete.AutoSizeLeftIcon = true;
            this.btn_delete.AutoSizeRightIcon = true;
            this.btn_delete.BackColor = System.Drawing.Color.Transparent;
            this.btn_delete.BackColor1 = System.Drawing.Color.Crimson;
            this.btn_delete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_delete.BackgroundImage")));
            this.btn_delete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.ButtonText = "Hapus";
            this.btn_delete.ButtonTextMarginLeft = 0;
            this.btn_delete.ColorContrastOnClick = 45;
            this.btn_delete.ColorContrastOnHover = 45;
            this.btn_delete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_delete.CustomizableEdges = borderEdges2;
            this.btn_delete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_delete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_delete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_delete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_delete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_delete.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_delete.ForeColor = System.Drawing.Color.White;
            this.btn_delete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_delete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_delete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_delete.IconMarginLeft = 11;
            this.btn_delete.IconPadding = 10;
            this.btn_delete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_delete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_delete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_delete.IconSize = 25;
            this.btn_delete.IdleBorderColor = System.Drawing.Color.Crimson;
            this.btn_delete.IdleBorderRadius = 15;
            this.btn_delete.IdleBorderThickness = 1;
            this.btn_delete.IdleFillColor = System.Drawing.Color.Crimson;
            this.btn_delete.IdleIconLeftImage = null;
            this.btn_delete.IdleIconRightImage = null;
            this.btn_delete.IndicateFocus = false;
            this.btn_delete.Location = new System.Drawing.Point(606, 433);
            this.btn_delete.Name = "btn_delete";
            this.btn_delete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_delete.OnDisabledState.BorderRadius = 15;
            this.btn_delete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.OnDisabledState.BorderThickness = 1;
            this.btn_delete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_delete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_delete.OnDisabledState.IconLeftImage = null;
            this.btn_delete.OnDisabledState.IconRightImage = null;
            this.btn_delete.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.btn_delete.onHoverState.BorderRadius = 15;
            this.btn_delete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.onHoverState.BorderThickness = 1;
            this.btn_delete.onHoverState.FillColor = System.Drawing.Color.Red;
            this.btn_delete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_delete.onHoverState.IconLeftImage = null;
            this.btn_delete.onHoverState.IconRightImage = null;
            this.btn_delete.OnIdleState.BorderColor = System.Drawing.Color.Crimson;
            this.btn_delete.OnIdleState.BorderRadius = 15;
            this.btn_delete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.OnIdleState.BorderThickness = 1;
            this.btn_delete.OnIdleState.FillColor = System.Drawing.Color.Crimson;
            this.btn_delete.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_delete.OnIdleState.IconLeftImage = null;
            this.btn_delete.OnIdleState.IconRightImage = null;
            this.btn_delete.OnPressedState.BorderColor = System.Drawing.Color.Maroon;
            this.btn_delete.OnPressedState.BorderRadius = 15;
            this.btn_delete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.OnPressedState.BorderThickness = 1;
            this.btn_delete.OnPressedState.FillColor = System.Drawing.Color.Maroon;
            this.btn_delete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_delete.OnPressedState.IconLeftImage = null;
            this.btn_delete.OnPressedState.IconRightImage = null;
            this.btn_delete.Size = new System.Drawing.Size(100, 35);
            this.btn_delete.TabIndex = 59;
            this.btn_delete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_delete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_delete.TextMarginLeft = 0;
            this.btn_delete.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_delete.UseDefaultRadiusAndThickness = true;
            this.btn_delete.Click += new System.EventHandler(this.btn_delete_Click);
            // 
            // btn_update
            // 
            this.btn_update.AllowAnimations = true;
            this.btn_update.AllowMouseEffects = true;
            this.btn_update.AllowToggling = false;
            this.btn_update.AnimationSpeed = 200;
            this.btn_update.AutoGenerateColors = false;
            this.btn_update.AutoRoundBorders = false;
            this.btn_update.AutoSizeLeftIcon = true;
            this.btn_update.AutoSizeRightIcon = true;
            this.btn_update.BackColor = System.Drawing.Color.Transparent;
            this.btn_update.BackColor1 = System.Drawing.Color.Orange;
            this.btn_update.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_update.BackgroundImage")));
            this.btn_update.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_update.ButtonText = "Edit";
            this.btn_update.ButtonTextMarginLeft = 0;
            this.btn_update.ColorContrastOnClick = 45;
            this.btn_update.ColorContrastOnHover = 45;
            this.btn_update.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_update.CustomizableEdges = borderEdges3;
            this.btn_update.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_update.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_update.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_update.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_update.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_update.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_update.ForeColor = System.Drawing.Color.White;
            this.btn_update.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_update.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_update.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_update.IconMarginLeft = 11;
            this.btn_update.IconPadding = 10;
            this.btn_update.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_update.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_update.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_update.IconSize = 25;
            this.btn_update.IdleBorderColor = System.Drawing.Color.Orange;
            this.btn_update.IdleBorderRadius = 15;
            this.btn_update.IdleBorderThickness = 1;
            this.btn_update.IdleFillColor = System.Drawing.Color.Orange;
            this.btn_update.IdleIconLeftImage = null;
            this.btn_update.IdleIconRightImage = null;
            this.btn_update.IndicateFocus = false;
            this.btn_update.Location = new System.Drawing.Point(493, 433);
            this.btn_update.Name = "btn_update";
            this.btn_update.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_update.OnDisabledState.BorderRadius = 15;
            this.btn_update.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_update.OnDisabledState.BorderThickness = 1;
            this.btn_update.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_update.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_update.OnDisabledState.IconLeftImage = null;
            this.btn_update.OnDisabledState.IconRightImage = null;
            this.btn_update.onHoverState.BorderColor = System.Drawing.Color.Gold;
            this.btn_update.onHoverState.BorderRadius = 15;
            this.btn_update.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_update.onHoverState.BorderThickness = 1;
            this.btn_update.onHoverState.FillColor = System.Drawing.Color.Gold;
            this.btn_update.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_update.onHoverState.IconLeftImage = null;
            this.btn_update.onHoverState.IconRightImage = null;
            this.btn_update.OnIdleState.BorderColor = System.Drawing.Color.Orange;
            this.btn_update.OnIdleState.BorderRadius = 15;
            this.btn_update.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_update.OnIdleState.BorderThickness = 1;
            this.btn_update.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.btn_update.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_update.OnIdleState.IconLeftImage = null;
            this.btn_update.OnIdleState.IconRightImage = null;
            this.btn_update.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.btn_update.OnPressedState.BorderRadius = 15;
            this.btn_update.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_update.OnPressedState.BorderThickness = 1;
            this.btn_update.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.btn_update.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_update.OnPressedState.IconLeftImage = null;
            this.btn_update.OnPressedState.IconRightImage = null;
            this.btn_update.Size = new System.Drawing.Size(100, 35);
            this.btn_update.TabIndex = 58;
            this.btn_update.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_update.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_update.TextMarginLeft = 0;
            this.btn_update.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_update.UseDefaultRadiusAndThickness = true;
            this.btn_update.Click += new System.EventHandler(this.btn_update_Click);
            // 
            // btn_insert
            // 
            this.btn_insert.AllowAnimations = true;
            this.btn_insert.AllowMouseEffects = true;
            this.btn_insert.AllowToggling = false;
            this.btn_insert.AnimationSpeed = 200;
            this.btn_insert.AutoGenerateColors = false;
            this.btn_insert.AutoRoundBorders = false;
            this.btn_insert.AutoSizeLeftIcon = true;
            this.btn_insert.AutoSizeRightIcon = true;
            this.btn_insert.BackColor = System.Drawing.Color.Transparent;
            this.btn_insert.BackColor1 = System.Drawing.Color.LimeGreen;
            this.btn_insert.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_insert.BackgroundImage")));
            this.btn_insert.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_insert.ButtonText = "Tambah";
            this.btn_insert.ButtonTextMarginLeft = 0;
            this.btn_insert.ColorContrastOnClick = 45;
            this.btn_insert.ColorContrastOnHover = 45;
            this.btn_insert.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_insert.CustomizableEdges = borderEdges4;
            this.btn_insert.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_insert.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_insert.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_insert.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_insert.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_insert.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btn_insert.ForeColor = System.Drawing.Color.White;
            this.btn_insert.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_insert.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_insert.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_insert.IconMarginLeft = 11;
            this.btn_insert.IconPadding = 10;
            this.btn_insert.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_insert.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_insert.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_insert.IconSize = 25;
            this.btn_insert.IdleBorderColor = System.Drawing.Color.LimeGreen;
            this.btn_insert.IdleBorderRadius = 15;
            this.btn_insert.IdleBorderThickness = 1;
            this.btn_insert.IdleFillColor = System.Drawing.Color.LimeGreen;
            this.btn_insert.IdleIconLeftImage = null;
            this.btn_insert.IdleIconRightImage = null;
            this.btn_insert.IndicateFocus = false;
            this.btn_insert.Location = new System.Drawing.Point(379, 433);
            this.btn_insert.Name = "btn_insert";
            this.btn_insert.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_insert.OnDisabledState.BorderRadius = 15;
            this.btn_insert.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_insert.OnDisabledState.BorderThickness = 1;
            this.btn_insert.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_insert.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_insert.OnDisabledState.IconLeftImage = null;
            this.btn_insert.OnDisabledState.IconRightImage = null;
            this.btn_insert.onHoverState.BorderColor = System.Drawing.Color.Lime;
            this.btn_insert.onHoverState.BorderRadius = 15;
            this.btn_insert.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_insert.onHoverState.BorderThickness = 1;
            this.btn_insert.onHoverState.FillColor = System.Drawing.Color.Lime;
            this.btn_insert.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_insert.onHoverState.IconLeftImage = null;
            this.btn_insert.onHoverState.IconRightImage = null;
            this.btn_insert.OnIdleState.BorderColor = System.Drawing.Color.LimeGreen;
            this.btn_insert.OnIdleState.BorderRadius = 15;
            this.btn_insert.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_insert.OnIdleState.BorderThickness = 1;
            this.btn_insert.OnIdleState.FillColor = System.Drawing.Color.LimeGreen;
            this.btn_insert.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_insert.OnIdleState.IconLeftImage = null;
            this.btn_insert.OnIdleState.IconRightImage = null;
            this.btn_insert.OnPressedState.BorderColor = System.Drawing.Color.Green;
            this.btn_insert.OnPressedState.BorderRadius = 15;
            this.btn_insert.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_insert.OnPressedState.BorderThickness = 1;
            this.btn_insert.OnPressedState.FillColor = System.Drawing.Color.Green;
            this.btn_insert.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_insert.OnPressedState.IconLeftImage = null;
            this.btn_insert.OnPressedState.IconRightImage = null;
            this.btn_insert.Size = new System.Drawing.Size(100, 35);
            this.btn_insert.TabIndex = 57;
            this.btn_insert.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_insert.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_insert.TextMarginLeft = 0;
            this.btn_insert.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_insert.UseDefaultRadiusAndThickness = true;
            this.btn_insert.Click += new System.EventHandler(this.btn_insert_Click);
            // 
            // pb_fotoFile
            // 
            this.pb_fotoFile.BackColor = System.Drawing.Color.White;
            this.pb_fotoFile.Location = new System.Drawing.Point(455, 302);
            this.pb_fotoFile.Name = "pb_fotoFile";
            this.pb_fotoFile.ShadowDecoration.Parent = this.pb_fotoFile;
            this.pb_fotoFile.Size = new System.Drawing.Size(178, 105);
            this.pb_fotoFile.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pb_fotoFile.TabIndex = 60;
            this.pb_fotoFile.TabStop = false;
            // 
            // FormManageMenu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(243)))), ((int)(((byte)(224)))));
            this.ClientSize = new System.Drawing.Size(720, 480);
            this.ControlBox = false;
            this.Controls.Add(this.btn_delete);
            this.Controls.Add(this.btn_update);
            this.Controls.Add(this.btn_insert);
            this.Controls.Add(this.btn_pickFile);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.txb_filePath);
            this.Controls.Add(this.cb_kategori);
            this.Controls.Add(this.guna2Panel1);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.dgv_manageMenu);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.txb_cari);
            this.Controls.Add(this.txb_hargaMenu);
            this.Controls.Add(this.btn_cari);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.txb_menuID);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.txb_namaMenu);
            this.Controls.Add(this.pb_fotoFile);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "FormManageMenu";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Atur Menu";
            this.Load += new System.EventHandler(this.FormManageMenu_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgv_manageMenu)).EndInit();
            this.guna2Panel1.ResumeLayout(false);
            this.guna2Panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.guna2PictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pb_fotoFile)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuTextBox txb_cari;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_cari;
        private Bunifu.UI.WinForms.BunifuDataGridView dgv_manageMenu;
        private Guna.UI2.WinForms.Guna2Panel guna2Panel1;
        private Guna.UI2.WinForms.Guna2PictureBox guna2PictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Guna.UI2.WinForms.Guna2ControlBox guna2ControlBox1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuDropdown cb_kategori;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox txb_hargaMenu;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox txb_menuID;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox txb_namaMenu;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox txb_filePath;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_pickFile;
        private Guna.UI2.WinForms.Guna2PictureBox pb_fotoFile;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_delete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_update;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_insert;
    }
}